apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: cluster-config
spec:
  interval: 10m0s
  dependsOn:
    - name: common
  sourceRef:
    kind: GitRepository
    name: cluster-config
  path: ./resources/apps
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-operator-kube-p-operator
      namespace: monitoring