---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-frontend-device1
  namespace: device1
spec:
  chart:
    spec:
      chart: demo-frontend
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: demo-frontend
        namespace: cluster-config
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: demo-frontend-device1
  targetNamespace: device1
