apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: common
  namespace: cluster-config
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
  path: ./resources/common
  prune: true
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: DaemonSet
  #     name: nginx-ingress-ingress-nginx-controller
  #     namespace: ingress-nginx