---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: super-api
  namespace: device2
spec:
  chart:
    spec:
      chart: super-api
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: super-api
        namespace: cluster-config
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: super-api-device2
